version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      MKTPLACE_DB__uri: "postgresql://postgres:postgres@db:5432/imoveis"
    volumes:
      - .:/home/app/api
    depends_on:
      - db
      - mongo

  db:
    image: postgres:13-alpine
    volumes:
      - $HOME/.postgres/mktplace_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: imoveis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - $HOME/.mongodb/data/:/data/db
